// Quiz questions for the Kinematics assessment.
// Each question: id, type, prompt, options (for MC), answer, explanation,
// optional katex formula for reinforcement.

export const QUIZ_QUESTIONS = [
  {
    id: "q1",
    type: "conceptual",
    prompt: "An object moves 5 m to the right, then 5 m back to where it started. What is its final displacement?",
    options: ["0 m", "5 m", "10 m", "25 m"],
    answer: 0,
    explanation: "Displacement depends only on start and end positions. Since the object returns to its start, displacement is 0 m — even though the distance travelled is 10 m.",
  },
  {
    id: "q2",
    type: "numerical",
    prompt: "A car accelerates uniformly from rest at 3 m/s² for 4 s. What is its final velocity?",
    answer: "12",
    unit: "m/s",
    tolerance: 0.1,
    explanation: "Using v = u + at with u = 0, a = 3, t = 4: v = 0 + 3×4 = 12 m/s.",
    formula: "v = u + at = 0 + (3)(4) = 12\\,\\text{m/s}",
  },
  {
    id: "q3",
    type: "graph",
    prompt: "On a position–time graph, an object shows a straight line sloping downward. What does this tell you about the velocity?",
    options: ["Constant positive velocity", "Constant negative velocity", "Zero velocity", "Increasing velocity"],
    answer: 1,
    explanation: "Slope of a position–time graph = velocity. A straight downward line means constant negative velocity (moving in the negative direction at steady speed).",
  },
  {
    id: "q4",
    type: "equation",
    prompt: "You know u, a and s, and need to find v — but you don't know t. Which equation should you use?",
    options: ["v = u + at", "s = ut + ½at²", "v² = u² + 2as", "s = ½(u+v)t"],
    answer: 2,
    explanation: "When time is unknown, use v² = u² + 2as. It relates v, u, a and s directly, without needing t.",
  },
  {
    id: "q5",
    type: "projectile",
    prompt: "For ideal projectile motion with equal launch and landing height, which angle gives the maximum range?",
    options: ["30°", "45°", "60°", "90°"],
    answer: 1,
    explanation: "Range R = u²sin(2θ)/g is maximised when sin(2θ) = 1, i.e. 2θ = 90°, so θ = 45°. At 90° the projectile goes straight up with zero range.",
  },
  {
    id: "q6",
    type: "conceptual",
    prompt: "Which of these is a vector quantity?",
    options: ["Distance", "Speed", "Displacement", "Time"],
    answer: 2,
    explanation: "Displacement is a vector — it has magnitude AND direction. Distance and speed are scalars (magnitude only). Time is also a scalar.",
  },
  {
    id: "q7",
    type: "graph",
    prompt: "What does the AREA under a velocity–time graph represent?",
    options: ["Acceleration", "Displacement", "Speed", "Force"],
    answer: 1,
    explanation: "Area under v–t graph = ∫v dt = displacement. Area under an a–t graph would give change in velocity.",
  },
  {
    id: "q8",
    type: "numerical",
    prompt: "A projectile is launched at 20 m/s at 30°. What is the horizontal velocity component? (cos30° ≈ 0.866)",
    answer: "17.3",
    unit: "m/s",
    tolerance: 0.3,
    explanation: "vx = u·cos(θ) = 20 × cos30° ≈ 20 × 0.866 = 17.3 m/s. The horizontal component stays constant (no air resistance).",
    formula: "v_x = u\\cos\\theta = 20\\cos 30^\\circ \\approx 17.3\\,\\text{m/s}",
  },
  {
    id: "q9",
    type: "projectile",
    prompt: "During the flight of an ideal projectile, which velocity component changes with time?",
    options: ["Only vx", "Only vy", "Both vx and vy", "Neither"],
    answer: 1,
    explanation: "Gravity acts vertically, so vy changes (vy = u sinθ − gt). With no air resistance, vx = u cosθ stays constant throughout the flight.",
  },
  {
    id: "q10",
    type: "numerical",
    prompt: "An object starts from rest and accelerates at 2 m/s². How far does it travel in 5 s?",
    answer: "25",
    unit: "m",
    tolerance: 0.2,
    explanation: "Using s = ut + ½at² with u = 0, a = 2, t = 5: s = 0 + ½×2×25 = 25 m.",
    formula: "s = ut + \\tfrac{1}{2}at^2 = 0 + \\tfrac{1}{2}(2)(5^2) = 25\\,\\text{m}",
  },
];
